{
 "title": "Distributed",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Sensor Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature Sensor",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"boiler-temp\"}"
    }
   ]
  },
  {
   "title": "Pressure Sensor",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"boiler-pressure\"}"
    }
   ]
  },
  {
   "title": "Current Sensor",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"boiler-current\"}"
    }
   ]
  },
  {
   "title": "Mixer RPM Sensor",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"boiler-mixer\"}"
    }
   ]
  },
  { "title": "Sensor Live", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Boiler Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sensor_reading{instance=\"monitoring:2112\",job=\"monitoring\",sensor=\"boiler-temp\"}"
    }
   ]
  },
  {
   "title": "Boiler Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "sensor_reading{sensor=\"boiler-pressure\"}"
    }
   ]
  },
  {
   "title": "Boiler Current",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sensor_reading{sensor=\"boiler-current\"}"
    }
   ]
  },
  {
   "title": "Boiler Mixer RPM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "sensor_reading{sensor=\"boiler-mixer\"}"
    }
   ]
  },
  { "title": "Sensor Reading Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Boiler Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "sensor_reading{sensor=\"boiler-temp\"}",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Boiler Pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "pressurebar" }
   ],
   "targets": [
    {
     "expr": "sensor_reading{sensor=\"boiler-pressure\"}",
     "legendFormat": "Pressure"
    }
   ]
  },
  {
   "title": "Boiler Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "sensor_reading{sensor=\"boiler-current\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Boiler Mixer RpM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sensor_reading{sensor=\"boiler-mixer\"}",
     "legendFormat": "Revolutions Per Minute"
    }
   ]
  },
  { "title": "Per-Tier Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Readings Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(coordinator_reading_count{layer=\"coordinator\"}[1m])) / 4",
     "legendFormat": "coordinator"
    },
    {
     "expr": "sum(irate(coordinator_reading_count{layer=\"monitoring\"}[1m])) / 4",
     "legendFormat": "monitoring"
    }
   ]
  },
  {
   "title": "Coordinator Tier",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(coordinator_reading_count{layer=\"coordinator\"}[20s])",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Monitoring Tier",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(coordinator_reading_count{layer=\"monitoring\"}[20s])",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Docker Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=\"running\"}"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Disk Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max ((node_filesystem_size_bytes - node_filesystem_free_bytes) * 100 / (node_filesystem_size_bytes))"
    }
   ]
  }
 ]
}